accessing
doubleMailFileContent

	^ 'Received: from MXSTU2012.hpi.uni-potsdam.de ([fe80::b539:e00:3268:a932]) by
 OWA-2012.hpi.uni-potsdam.de ([fe80::9d94:d459:bf45:5d57%22]) with mapi id
 14.03.0210.002; Sat, 15 Nov 2014 01:35:26 +0100
From: "Hoasd, Askdjas" <hoasd.askdjas@uni-potsdam.de>
To: Rein, Patrick" <Patrick.Rein@hpi.de>, "Uio
 Fdf (uio.fdf@gmail.com)" <uio.fdf@gmail.com>
Subject: Ski fahren?
Thread-Topic: Ski fahren?
Thread-Index: AdAAa8EJMxDuxnv/RkCZwR3Ig6ITLw==
X-MS-Exchange-MessageSentRepresentingType: 1
Date: Sat, 15 Nov 2014 01:35:25 +0100
Message-ID:
	<A5D573DC3A4D504E94F179A430DB329E0E0DAE6F@MXSTU2012.hpi.uni-potsdam.de>
Accept-Language: de-DE, en-US
Content-Language: de-DE
X-MS-Exchange-Organization-AuthAs: Internal
X-MS-Exchange-Organization-AuthMechanism: 04
X-MS-Exchange-Organization-AuthSource: OWA-2012.hpi.uni-potsdam.de
X-MS-Has-Attach:
X-MS-Exchange-Organization-SCL: -1
X-MS-TNEF-Correlator:
x-originating-ip: [141.89.225.161]
Content-Type: text/html; charset="us-ascii"
MIME-Version: 1.0

<html xmlns:v="urn:schemas-microsoft-com:vml" xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:w="urn:schemas-microsoft-com:office:word" xmlns:m="http://schemas.microsoft.com/office/2004/12/omml" xmlns="http://www.w3.org/TR/REC-html40">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=us-ascii">
<meta name="Generator" content="Microsoft Word 14 (filtered medium)">
<style><!--
/* Font Definitions */
@font-face
	{font-family:Calibri;
	panose-1:2 15 5 2 2 2 4 3 2 4;}
/* Style Definitions */
p.MsoNormal, li.MsoNormal, div.MsoNormal
	{margin:0cm;
	margin-bottom:.0001pt;
	font-size:11.0pt;
	font-family:"Calibri","sans-serif";
	mso-fareast-language:EN-US;}
a:link, span.MsoHyperlink
	{mso-style-priority:99;
	color:blue;
	text-decoration:underline;}
a:visited, span.MsoHyperlinkFollowed
	{mso-style-priority:99;
	color:purple;
	text-decoration:underline;}
span.E-MailFormatvorlage17
	{mso-style-type:personal-compose;
	font-family:"Calibri","sans-serif";
	color:windowtext;}
.MsoChpDefault
	{mso-style-type:export-only;
	font-family:"Calibri","sans-serif";
	mso-fareast-language:EN-US;}
@page WordSection1
	{size:612.0pt 792.0pt;
	margin:70.85pt 70.85pt 2.0cm 70.85pt;}
div.WordSection1
	{page:WordSection1;}
--></style><!--[if gte mso 9]><xml>
<o:shapedefaults v:ext="edit" spidmax="1026" />
</xml><![endif]--><!--[if gte mso 9]><xml>
<o:shapelayout v:ext="edit">
<o:idmap v:ext="edit" data="1" />
</o:shapelayout></xml><![endif]-->
</head>
<body lang="EN-GB" link="blue" vlink="purple">
<div class="WordSection1">
<p class="MsoNormal"><span lang="DE">Aber sicher!<o:p></o:p></span></p>
</div>
</body>
</html>'