fixtures
addedMailFileContent

	^ 'Delivered-To: patrick.rein@gmail.com
To: patrick.rein@gmail.com
Subject: Asd has invited you to join CDG Labs on Slack
Reply-To: asd@gmail.com
In-reply-to: <20141113225959.C20CD25738@slack-www140.tinyspeck.com>
From: "Slack" <feedback@slack.com>
Mime-Version: 1.0
Content-Type: multipart/alternative; boundary="__slack_304307350__"
Message-Id: <20171113225959.C20CD25738@slack-www140.tinyspeck.com>
Date: Thu, 13 Nov 2017 14:59:59 -0800 (PST)
Sender: feedback@slack.com

--__slack_304307350__
Content-Type: text/plain; charset="utf-8"
Content-Transfer-Encoding: quoted-printable
Content-Disposition: inline

Welcome again

you are doing just fine.

--__slack_304307350__--'